import DarkIcon from "../components/TypeComponents/DarkIcon"
import FairyIcon from "../components/TypeComponents/FairyIcon"
import FireIcon from "../components/TypeComponents/FireIcon"
import FlyingIcon from "../components/TypeComponents/FlyingIcon"
import WaterIcon from "../components/TypeComponents/WaterIcon"
import Steel from "../components/TypeComponents/Steel"
import Grass from "../components/TypeComponents/Grass"
import GhostIcon from "../components/TypeComponents/GhostIcon"
import Normalcon from "../components/TypeComponents/Normalcon"
import Thunder from "../components/TypeComponents/Thunder"




const getRaremon = () => {
    return {
        "wyvie" : {
            "fire" : {
                "image" : "wyvie/1stStage/fireType.png",
                "darkImage" : "wyvie/1stStage/fireTypeDark.png",
                "discovered" : false,
                'component': <FireIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "wyvie/1stStage/basicForm.png",
                "darkImage" : "wyvie/1stStage/basicFormDark.png",
                "discovered" : true,
                'component': <Normalcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "wyvie/1stStage/waterType.png",
                "darkImage" : "wyvie/1stStage/waterTypeDark.png",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "wyvie/1stStage/grassType.png",
                "darkImage" : "wyvie/1stStage/grassTypeDark.png",
                "discovered" : false,
                'component': <Grass/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "wyvie/1stStage/darkType.png",
                "darkImage" : "wyvie/1stStage/darkTypeDark.png",
                "discovered" : true,
                'component': <DarkIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "wyvie/1stStage/electricType.png",
                "darkImage" : "wyvie/1stStage/electricTypeDark.png",
                "discovered" : true,
                'component': <Thunder/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "wyvie/1stStage/steelType.png",
                "darkImage" : "wyvie/1stStage/steelTypeDark.png",
                "discovered" : true,
                'component': <Steel/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "wyvie/1stStage/fairyType.png",
                "darkImage" : "wyvie/1stStage/fairyTypeDark.png",
                "discovered" : true,
                'component': <FairyIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "wyvie/1stStage/windType.png",
                "darkImage" : "wyvie/1stStage/windTypeDark.png",
                "discovered" : true,
                'component': <FlyingIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "wyvie/1stStage/ghostType.png",
                "darkImage" : "wyvie/1stStage/ghostTypeDark.png",
                "discovered" : true,
                'component': <GhostIcon/>,
                'colour': "blue",
            },
        },
        "wyvie2nd" : {
            "fire" : {
                "image" : "wyvie/2ndStage/fireTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "wyvie/2ndStage/basicFormDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "wyvie/2ndStage/waterTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "wyvie/2ndStage/grassTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "wyvie/2ndStage/darkTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "wyvie/2ndStage/electricTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "wyvie/2ndStage/steelTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "wyvie/2ndStage/fairyTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "wyvie/2ndStage/windTypeDarkDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "wyvie/2ndStage/ghostTypeDark.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        "wyvie3rd" : {
            "fire" : {
                "image" : "wyvie/3rdStage/fireType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "wyvie/3rdStage/basicForm.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "wyvie/3rdStage/waterType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "wyvie/3rdStage/grassType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "wyvie/3rdStage/darkType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "wyvie/3rdStage/electricType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "wyvie/3rdStage/steelType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "wyvie/3rdStage/fairyType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "wyvie/3rdStage/windType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "wyvie/3rdStage/ghostType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        "lupo" : {
            "fire" : {
                "image" : "lupo/1stStage/fireType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "lupo/1stStage/basicForm.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "lupo/1stStage/waterType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "lupo/1stStage/grassType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "lupo/1stStage/darkType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "lupo/1stStage/electricType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "lupo/1stStage/steelType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "lupo/1stStage/fairyType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "lupo/1stStage/windType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "lupo/1stStage/ghostType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        "lupo2nd" : {
            "fire" : {
                "image" : "lupo/2ndStage/fireType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "lupo/2ndStage/basicForm.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "lupo/2ndStage/waterType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "lupo/2ndStage/grassType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "lupo/2ndStage/darkType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "lupo/2ndStage/electricType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "lupo/2ndStage/steelType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "lupo/2ndStage/fairyType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "lupo/2ndStage/windType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "lupo/2ndStage/ghostType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        "lupo3rd" : {
            "fire" : {
                "image" : "lupo/3rdStage/fireType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "lupo/3rdStage/basicForm.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "lupo/3rdStage/waterType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "lupo/3rdStage/grassType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "lupo/3rdStage/darkType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "lupo/3rdStage/electricType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "lupo/3rdStage/steelType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "lupo/3rdStage/fairyType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "lupo/3rdStage/windType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "lupo/3rdStage/ghostType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        "squark 1st" : {
            "fire" : {
                "image" : "squark/1stStage/fireType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "normal" : {
                "image" : "squark/1stStage/basicForm.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "water" : {
                "image" : "squark/1stStage/waterType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "grass" : {
                "image" : "squark/1stStage/grassType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "dark" : {
                "image" : "squark/1stStage/darkType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "lightning" : {
                "image" : "squark/1stStage/electricType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "steel" : {
                "image" : "squark/1stStage/steelType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "fairy" : {
                "image" : "squark/1stStage/fairyType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "wind" : {
                "image" : "squark/1stStage/windType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
            "ghost" : {
                "image" : "squark/1stStage/ghostType.png",
                "darkImage" : "",
                "discovered" : true,
                'component': <WaterIcon/>,
                'colour': "blue",
            },
        },
        
        
    }
}

export default getRaremon